@API = http://localhost:3000/ventas

get {{API}}

###
POST {{API}}
Content-Type: application/json

{
    "tarea":"5 tarea a realizar",
    "fecha":"2022-05-31Z01:12:12"
}

###
GET {{API}}/T001/4000


###
DELETE {{API}}/5

###
GET {{API}}/count


###
GET {{API}}/grupo/T001/12/8
